# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WsnZHJPRnhWxeVJtEnzSC_a_3LnViCm
"""

# Cell 1 - Importing all necessary libraries

import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical

print("TensorFlow version:", tf.__version__)
print("All libraries imported successfully!")

# Cell 2 - Load CIFAR-10 directly in Google Colab

from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical

(x_train, y_train), (x_test, y_test) = cifar10.load_data()


x_train = x_train / 255.0
x_test = x_test / 255.0


y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

print("Training data shape:", x_train.shape)
print("Testing data shape:", x_test.shape)

# Cell 3 - Building the CNN Model

model = models.Sequential([

    # First Convolutional Block
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),

    # Second Convolutional Block
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Third Convolutional Block
    layers.Conv2D(64, (3, 3), activation='relu'),


    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])


model.summary()

# Cell 4 - Compile and Train the Model

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=64,
                    validation_data=(x_test, y_test))

# Cell 5 - Evaluate and Plot Results

test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {test_accuracy*100:.2f}%")
print(f"Test Loss: {test_loss:.4f}")

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

# Cell 6 - Predict and Visualize Sample Images

class_names = ['airplane', 'car', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

import numpy as np
indices = np.random.randint(0, len(x_test), 10)
sample_images = x_test[indices]
sample_labels = y_test[indices]

predictions = model.predict(sample_images)

plt.figure(figsize=(15, 4))
for i in range(10):
    plt.subplot(2, 5, i+1)
    plt.imshow(sample_images[i])

    predicted = class_names[np.argmax(predictions[i])]
    actual = class_names[np.argmax(sample_labels[i])]

    color = 'green' if predicted == actual else 'red'
    plt.title(f"P: {predicted}\nA: {actual}", color=color, fontsize=8)
    plt.axis('off')

plt.tight_layout()
plt.show()

y_classes = np.argmax(model.predict(x_test), axis=1)

classes = ['airplane', 'car', 'bird', 'cat', 'deer',
           'dog', 'frog', 'horse', 'ship', 'truck']

def plot_sample(x, y, index):
    plt.imshow(x[index])
    plt.title(f"Actual: {classes[np.argmax(y[index])]}")
    plt.axis('off')
    plt.show()

plot_sample(x_test, y_test, 1)
print("Predicted class:", classes[y_classes[2]])

#checking various images
plot_sample(x_test, y_test, 16)
print("Predicted:", classes[y_classes[16]])

plot_sample(x_test, y_test, 155)
print("Predicted:", classes[y_classes[15]])

